poll/urls.py
from django.conf.urls import url
from . import views

app_name = 'poll'
urlpatterns = [
    url(r'^$',                           views.list,   name='poll_list'),
    url(r'^(?P<pk>\d+)/$',               views.detail, name='poll_detail'),
    url(r'^(?P<pk>\d+)/result/$',        views.result, name='poll_result'),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote,   name='poll_vote'),
]

poll/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils import timezone
import datetime
from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200, verbose_name='설문제목')
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200, verbose_name='항목')
    votes = models.IntegerField(default=0, verbose_name='응답수')
    def __str__(self):
        return self.choice_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

poll/views.py
from django.shortcuts import get_object_or_404, render
from .models import Choice, Question

def list(request):
    list = Question.objects.order_by('-pub_date')[:5]
    return render(request, 'poll/poll_list.html', {'latest_question_list':list})

def detail(request, pk):
    question = get_object_or_404(Question, pk=pk)
    choice_set = Choice.objects.filter(question=pk)
    return render(request, 'poll/poll_detail.html', {'question':question, 'choice_set':choice_set})

def result(request, pk):
    question = get_object_or_404(Question, pk=pk)
    choice_set = Choice.objects.filter(question=pk)
    return render(request, 'poll/poll_results.html', {'question':question, 'choice_set':choice_set})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = Choice.objects.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'poll/poll_detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return result(request, question_id)

poll/templates/poll/poll_detail.html
{% extends 'main/layout.html' %}

{% block title %}{{ question.question_text }}{% endblock %}

{% block content %}

    <h1>{{ question.question_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'poll:poll_vote' question.id %}" method="post">

    {% csrf_token %}
    <ul>
    {% for choice in choice_set %}
        <li><input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />{{ choice.choice_text }}</li>
    {% endfor %}
    </ul>

    <input type="submit" value="Vote" />
    </form>

{% endblock %}

poll/templates/poll/poll_list.html
{% extends 'main/layout.html' %}

{% block title %}Pegasus Poll{% endblock %}

{% block content %}

    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'poll:poll_detail' pk=question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}

{% endblock %}

poll/templates/poll/poll_results.html
{% extends 'main/layout.html' %}

{% block title %}{{ question.question_text }}{% endblock %}

{% block content %}

    <style>
        span .item {}
        span .cnt {position:absolute;right:0;}
    </style>


    <h1>{{ question.question_text }}</h1>

    <table>
    {% for choice in choice_set %}
        <tr>
            <td class='t'>{{ choice.choice_text }}</td>
            <td class='n'>{{ choice.votes }}</td>
            <td class='t'>vote{{ choice.votes|pluralize }}</td>
        </tr>
    {% endfor %}
    </table>

    <a href="{% url 'poll:poll_detail' question.id %}" class='btn'>VOTE AGAIN?</a>

{% endblock %}