blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.blog_list, name='blog_list'),
    url(r'^(?P<pk>\d+)/$', views.blog_detail, name='blog_detail'),
    url(r'^(?P<pk>\d+)/edit/$', views.blog_edit, name='blog_edit'),
    url(r'^new/$', views.blog_new, name='blog_new'),
    url(r'^(?P<pk>\d+)/delete/$', views.blog_delete, name='blog_delete'),
    url(r'^category/$', views.blog_category_count, name='blog_category_count'),

    url(r'^(?P<pk>\d+)/comment/$', views.comment_list, name='blog_comment_list'),
    url(r'^(?P<pk>\d+)/comment/new/$', views.comment_new, name='blog_comment_new'),
    url(r'^(?P<pk>\d+)/comment/(?P<id>\d+)/delete/$', views.comment_delete, name='blog_comment_delete'),
]

blog/templates/blog/blog_detail.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}{{ post.title }}{% endblock %}

{% block custom_style %}
        <style>
        td.writer, td.btn {border:0;}
        td.writer {color:#000;font-weight:bold;}
        td.writer span {margin-left:10px;color:#555;font-weight:normal;}
        td.btn {text-align:right;}
        td.btn img {width:15px;height:15px;}
        </style>
{% endblock custom_style %}

{% block custom_script %}
        <script>
        {% if request.user.is_authenticated %}
            {% if post_author == request.user %}
        function dropConfirm() {
            if(confirm('정말 삭제하시겠습니까?')) {
                location.href = '{% url 'blog:blog_delete' pk=post.pk %}';
            }
        }
            {% endif %}

        {% endif %}

        function getCommentRow(author, dt, id, comment) {
            str  = '';
            str += '<tr id="comment_'+id+'_head">';
            str += '<td class="writer" nowrap>';
            str += author;
            str += '<span>('+dt+')</span>';
            str += '</td>';
            str += '<td class="btn">';
            {% if request.user.is_authenticated %}
            if ('{{request.user}}'==author) {
                str += '<img src="{% static 'images/btnDrop.png' %}" onclick="dropComment('+id+');">';
            }
            {% endif %}
            str += '</td>';
            str += '</tr>';
            str += '<tr id="comment_'+id+'_tail"><td colspan="2">'+comment+'</td></tr>\n';
            return str;
        }

        function regist() {
            {% if request.user.is_authenticated %}
            var params = $("#frmEnt").serialize();
            $.ajax({
                url:"{% url 'blog:blog_comment_new' pk=post.pk %}",
                type:'post',
                data:params,
                success:function(result) {
                    $('#articlecomment').append(getCommentRow("{{request.user}}", "방금전", result, $("#comment").val()));
                    $("#comment").val("");
                }
            });
            {% endif %}
        }

        </script>
{% endblock custom_script %}

{% block custom_actions %}
    {% if request.user.is_authenticated %}
        {% if post_author == request.user %}
            <a href='{% url 'blog:blog_edit' pk=post.pk %}'>EDIT</a>
            <a href='javascript:dropConfirm()'>DROP</a>
        {% endif %}
        <a href='{% url 'blog:blog_new' %}'>NEW</a>
    {% endif %}
{% endblock custom_actions %}

{% block location %}
    &nbsp;&nbsp;/&nbsp;&nbsp;<a href='{% url 'blog:blog_list' %}'>BLOG</a>
    &nbsp;&nbsp;/&nbsp;&nbsp;<a href='{% url 'blog:blog_list' %}?cat={{ post.category.pk }}'>{{ post.category.category_name }}</a>
{% endblock %}

{% block content %}
    <div class="post">
        <h1 class='title'>{{ post.title }}</h1>

        <div class="subtitle">
            {% if post.published_date %}
            <p style='padding-bottom:15px;'>{{post.published_date}}&nbsp;|&nbsp;{{ post.category.category_name }}</p>
            <!-- span>PUBLISHED {{ post.published_date|date:"Y.m.d" }} {{ post.published_date|time:"H:i" }}</span -->
            <p>
            {% endif %}
            <span><a href='{% url 'blog:blog_list' %}?page={{page}}{% if category %}&cat={{category}}{% endif %}'>목록으로</a></span>
            <span id="speak">
                <a href="#articlecontent" onclick="speakStart();return false;" title="소리내어 내용 읽기">내용읽기</a>
                <a href="#articlecontent" onclick="speakContinue();return false;" title="소리내어 이어 읽기">이어읽기</a>
                <a href="#articlecontent" onclick="speakStop();return false;" title="그만 읽기">그만읽기</a>
            </span>
            </p>
        </div>

        <div>&nbsp;</div>

        <div>
            {% for f in files %}
            <img class='article_imgs' src='{{f.img.url}}' title='{{ f.img.name }}' />
            {% endfor %}
            <div id='articlecontent'>
                {# autoescape off #}
                    {{ post.text|linebreaksbr|urlize }}
                {# endautoescape #}
             </div>
            </div>

        {% if request.user.is_authenticated %}
        <form name="frmEnt" id="frmEnt" method="post" onsubmit="regist();return false;">
            {% csrf_token %}
            <input type='hidden' name='page' value='{{page}}'>
            <input type='hidden' name='cat' value='{% if category %}{{category}}{% endif %}'>
            <input type="text" name="comment" id="comment" style="width:100%;" placeholder="당신의 생각을 덧붙이세요. 엔터키를 누르면 저장됩니다." title="댓글등록, 댓글을 쓰시고 엔터키를 누르면 저장됩니다.">
        </form>
        {% endif %}

        <table id='articlecomment' style="width:100%;">
            <colgroup>
                <col style="width:*;">
                <col style="width:20px;">
            </colgroup>
            <tbody></tbody>
        </table>

    </div>

    <script src='{% get_static_prefix %}js/SpeechText.js?00004' type='text/javascript'></script>
    <script type='text/javascript'>
        var start = false;
        var st = new SpeechText('59d225a9634d334550e6a834', 'ko-KR', 'articlecontent');
        function speakStart() {
        	st.start();
        	start = true;
        };
        function speakContinue() {
        	st.keepon();
        	start = true;
        };
        function speakStop() {
        	st.stop();
        	start = false;
        };
        st.msg.onend = function(e) {
        	if (start) speakContinue();
        };

        {% if request.user.is_authenticated %}
        function dropComment(id) {
            $.ajax({
                url:"{% url 'blog:blog_comment_list' pk=post.pk %}"+id +"/delete/",
                success:function(result) {
                    console.log(result);
                    $("#comment_"+result+"_head").fadeOut();
                    $("#comment_"+result+"_tail").fadeOut();
                }
            });
        }
        {% endif %}

        $(document).ready(function(){
            $.ajax({
                url:"{% url 'blog:blog_comment_list' pk=post.pk %}",
                success:function(data) {
                    var d = eval(data);
                    var str = "";
                    for (var n in d) {
                        str += getCommentRow(d[n]['author'], d[n]['dt'], d[n]['id'], d[n]['comment']);
                    }
                    $('#articlecomment').html(str);
                    // console.log($('#articlecomment').html());
                }
            });
        });

    </script>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'main/layout.html' %}
{% load staticfiles %}

{% block title %}{{ strPageTitle }} - 생각을 기록하고 나누세요!{% endblock %}

{% block custom_style %}
        <style>
        li {list-style-type:none;min-height:40px;}
        select {height:37px;}
        input[type=file] {padding-left:0;border:0;width:250px;}
        label[for$='clear_id'], input[id$='clear_id'] {display:none;}
        label[for$='DELETE'] {margin-left:90px;margin-top:-5px;font-weight:normal;width:30px;}
        button {margin-left:90px;}
        iframe {margin-left:90px;margin-top:-30px;}

        @media only screen and (max-width : 700px) {
               label[for$='DELETE'] {display:block;margin-left:0;}
        }
        </style>
{% endblock custom_style %}

{% block custom_script %}
        <!-- script type="text/javascript" src="{% static 'editor/HuskyEZCreator.js' %}" charset="utf-8"></script -->
        <script type="text/javascript">
            function save() {
                //oEditors[0].exec("UPDATE_CONTENTS_FIELD", []);
                //document.getElementById('id_text').value;
                document.frmEnt.submit();
            }
        </script>
{% endblock custom_script %}

{% block custom_actions %}
    {% if request.user.is_authenticated %}
        {% if post_author == request.user %}
            <a href='javascript:history.go(-1);'>GO BACK</a>
        {% endif %}
        <a href='{% url 'blog:blog_new' %}'>NEW POST</a>
    {% endif %}
{% endblock custom_actions %}


{% block location %}
    &nbsp;&nbsp;|&nbsp;&nbsp;<a href='{% url 'blog:blog_list' %}'>BLOG</a>
    &nbsp;&nbsp;|&nbsp;&nbsp;<a href='#'>{{ strPageTitle }}</a>
{% endblock location %}


{% block content %}

    <!--h1 class='title'>{{ strPageTitle }}</h1>
    <div class="subtitle">생각을 기록하고 나누세요!</div -->

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            {{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}

    <div id='articlecontent'>
        <form method="POST" name='frmEnt' enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_ul }}
        {{ fileform.as_ul }}
        <div id='btns'><a href="javascript:save();" class='btn'>저장</a></div>
        </form>
    </div>


    <!-- script type="text/javascript">
        var oEditors = [];
            nhn.husky.EZCreator.createInIFrame({
            oAppRef: oEditors,
            elPlaceHolder: "id_text",
            sSkinURI: "{% static 'editor/skin.html' %}",
            htParams : {fOnBeforeUnload : function(){},
                        fOnAppLoad : function(){}
                        },
            fCreator: "createSEditor2"
        });
        </script -->

{% endblock content %}

blog/templates/blog/blog_list.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}Blog List{% endblock %}

{% block custom_actions %}
    <a href='{% url 'blog:blog_new' %}'>NEW POST</a>
{% endblock custom_actions %}

{% block location %}
    &nbsp;&nbsp;/&nbsp;&nbsp;<a href='{% url 'blog:blog_list' %}'>BLOG</a>
    {% if category %}
        &nbsp;&nbsp;/&nbsp;&nbsp;<a href='{% url 'blog:blog_list' %}?cat={{ category }}'>{{ category_name }}</a>
    {% endif %}
{% endblock %}

{% block content %}

    <script src="{% get_static_prefix %}js/pagination.js" type="text/javascript"></script>
    <style>
        .articlesummary {padding-top:14px;color:#888;}
        .delimeter {height:20px;border-bottom:1px solid #ddd;}
    </style>

    {% for post in posts %}
        <h1 class='title'><a href="{% url 'blog:blog_detail' pk=post.pk %}?page={{posts.number}}{% if category %}&cat={{ category }}{% endif %}">{{ post.title }}</a></h1>
        <div class="subtitle">{{ post.published_date }} <a href='?cat={{ post.category.pk }}'>{{ post.category.category_name }}</a></div>
        <div class='articlecontent'>{{ post.text|safe|striptags|truncatechars:400 }}</div>
        <div class='delimeter'></div>
        <div>&nbsp;</div>
    {% endfor %}

    <div id="pagination">
        <script>getPaging({{ posts.number }}, {{ totalcnt }}, {{ pagesize }}, 10, '{% if category %}&cat={{ category }}{% endif %}'); </script>
    </div>


{% endblock %}

blog/templates/blog/loadCategory.html
    <p>&nbsp;</p>

    <script type='text/javascript'>
        $(document).ready(function(){
        	$.ajax({
        		url:'/blog/category/',
        		success:function(r) {
        		    $('#section_pop_menu').append(r);
        		}
        	});
        });
    </script>